/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/run/numberOfThreads 1
/random/setSeeds 13580 24681
/det/scintillator OPSC-101
/det/readout EndTop
/sipm/model AFBR-S4N66P024M

/run/initialize

/display/maxOpticalTrajectories 20
/display/storeMuon true
/display/storeOtherParticles false

/sipm/jitterSigma 0 ns

/gun/particle mu-
/gun/energy 1 GeV
/gun/position 0 0 60 mm
/gun/direction 0 0 -1
/muon/gunX -400 mm
/muon/angle 0

/run/beamOn 1
